### ISSUE TITLE
tivoli listing improperly parsed

### ISSUE THREAD

**Issue by grf** [daitss/silo-pool#4]
tsmexecutor.rb  calls out to dsmc to get a listing from tivilo tapes.

For very large files (> 100GB), the listing is presented in KB (1024 bytes) units instead of B (bytes).
This has been fixed, I'm adding the issue for documentation

**Comment by grf** [comment]
fixed for KB, MB cases of units. KB case tested via the tivoli-ls program against the problem tape.

**Comment by avatar382** [comment]
So all that needs to be done is to roll the updated code to production so that the fixity check passes and silo 58 can be recycled?
