### ISSUE TITLE
URGENT: silotape.rb inconsistent with tsmexecutor.rb; prevents access to tape data

### ISSUE THREAD

**Issue by childree** [daitss/silo-pool#8]
Ira,

When silo-pool/lib/store/tsmexecutor.rb code, line 181, code was changed back on June 5, 2012, it mentions 3 arguments `path, destination, tivoli_owner,timeout = nil`.  This change broke silo-pool/lib/store/silotape.rb code because it references only 2 of the 3 arguments `path, destination, timeout = nil`.  We need silotape.rb to reference the argument `tivoli_owner`.  It is preventing me from accessing the content on the tapes.

Thank you,
Jen

**Comment by childree** [comment]
I will test this when I get back from lunch.  Thanks Ira!

**Comment by iterman** [comment]
rolled out code to ripple that should overcome this problem.

**Comment by childree** [comment]
I ran a test package through and it was successful.  Can we roll-out code tomorrow morning since it is so late today?

**Comment by childree** [comment]
This has been fixed in production with the latest code roll-out.  I'm able to successfully curl and view materials on the tapes.  Thank you!  I'm setting this ticket as resolved.
